"""nullable=True

Revision ID: 3e4ee03d88d0
Revises: a952c980900e
Create Date: 2024-07-22 10:04:14.855072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4ee03d88d0'
down_revision: Union[str, None] = 'a952c980900e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('settings', 'num_days_reminder',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('settings', 'num_days_benefit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vehicles', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('settings', 'num_days_benefit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('settings', 'num_days_reminder',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
