"""delete 2 fields in Parking_session

Revision ID: 5ecce3388348
Revises: cfd3ab984560
Create Date: 2024-07-27 17:21:03.488852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecce3388348'
down_revision: Union[str, None] = 'cfd3ab984560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'total_cost')
    op.drop_column('sessions', 'empty_place')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('empty_place', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('total_cost', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
