"""add end_date to Vehicle

Revision ID: 9e5efa95a871
Revises: 3e4ee03d88d0
Create Date: 2024-07-26 18:40:37.169930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5efa95a871'
down_revision: Union[str, None] = '3e4ee03d88d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'end_date')
    # ### end Alembic commands ###
