"""Update Role enum to replace guest with operator

Revision ID: ca4296526639
Revises: 5ecce3388348
Create Date: 2024-07-29 12:49:31.896623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca4296526639'
down_revision: Union[str, None] = '5ecce3388348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
        existing_type=postgresql.ENUM('admin', 'user', 'guest', name='role'),
        type_=postgresql.ENUM('admin', 'user', 'operator', name='role'),
        postgresql_using='role::text::role',
        nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
        existing_type=postgresql.ENUM('admin', 'user', 'operator', name='role'),
        type_=postgresql.ENUM('admin', 'user', 'guest', name='role'),
        postgresql_using='role::text::role',
        nullable=False)
    # ### end Alembic commands ###
