"""add end_date to Vehicle v2

Revision ID: cfd3ab984560
Revises: 9e5efa95a871
Create Date: 2024-07-26 19:09:03.952221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd3ab984560'
down_revision: Union[str, None] = '9e5efa95a871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('ended_at', sa.Date(), nullable=True))
    op.drop_column('vehicles', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('vehicles', 'ended_at')
    # ### end Alembic commands ###
