"""240325 - add public_photo_id

Revision ID: 8582d29e22fc
Revises: 1124751a6462
Create Date: 2024-03-26 01:57:31.392219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8582d29e22fc'
down_revision: Union[str, None] = '1124751a6462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('public_photo_id', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'public_photo_id')
    # ### end Alembic commands ###
